site_name: "Kimmy's Wiki"
docs_dir: content
theme:
  name: material
  features:
    - navigation.tabs
plugins:
  - search
  - meta-descriptions
  - ezlinks
  - callouts

markdown_extensions:
  - footnotes
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home:
    - index.md
    - 站点目录.md
    - 关于我.md
  - articles/文章列表.md
  - collect/收藏夹.md
  - publications/出版作品.md

copyright: Copyright &copy; 2013 - 2026 Kimmy Liu. <a href="https://beian.miit.gov.cn/">鲁ICP备2026030701号</a>
